### ISSUE TITLE
Nice job using IDs to style h2s

### ISSUE THREAD

**Issue by jzhu01** [VictorNellemann/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/VictorNellemann/prj-rev-bwfs-dasmoto/blob/master/DasMotoWebsite/resources/index.css#L22-L32

I like how you chose to implement this code with IDs! Since each h2 is unique in their background color, it's the more logical choice. 👍

**Comment by VictorNellemann** [comment]
👍
