### ISSUE TITLE
SUMMARY: Satisfactory

### ISSUE THREAD

**Issue by jzhu01** [VictorNellemann/prj-rev-bwfs-dasmoto#5]
Great job on this project! I really liked your usage of spans, your usage of IDs, and how clean and efficient your code is. In terms of improvement, I recommend removing the font-weight:bold on your h1 and h2s. 

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the nice work! ^_^

**Comment by VictorNellemann** [comment]
Thank you @jzhu01 . Thank you for your review and feedback. Your good point about the H1 and 2 is noted. How does it work, should I change the CSS to match it, or just apply the learning to coming code project in your class?

And lastly, to get the DasMoto project done in CodeAcademy, what do I need to do - Close the GitHub issues from you?

Best regards,
Victor

**Comment by jzhu01** [comment]
Great questions! 

On the topic of the h1 and h2, all you need to do is remove it from the CSS (the font-weight: bold).
 
And yes, you can just close the issues, and you're pretty much all set! Happy coding! :smile:
